"""seat_number

Revision ID: ac601dc959ac
Revises: e239866fc564
Create Date: 2025-05-17 14:46:55.611134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac601dc959ac'
down_revision: Union[str, None] = 'e239866fc564'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('dialog_step_key', 'dialog_step', ['id'])
    # ### end Alembic commands ###
    op.add_column('tickets', sa.Column('seat_number', sa.String(), nullable=True))
    conn = op.get_bind()
    conn.execute(sa.text("UPDATE public.tickets SET seat_number = id || '_' || flight_id;"))
    op.alter_column('tickets', column_name='seat_number', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tickets', 'seat_number')
    op.drop_constraint('dialog_step_key', 'dialog_step', type_='unique')
    # ### end Alembic commands ###
